name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Lint & Format check
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run isort --check .
